from __future__ import annotations
import streamlit as st


def render(registry, recommender, profiles, company) -> None:
    """Render the help page."""

    st.markdown(
        '<div class="page-header"><h1>How the system works</h1>'
        '<p class="lead">Finance Decision Studio is a governed ML platform that turns historical data '
        'into credit risk scores and demand forecasts, with full version control and human oversight.</p></div>',
        unsafe_allow_html=True,
    )

    # -- Mission ----------------------------------------------------------------
    st.markdown("### Mission")
    st.markdown(
        "This platform provides a structured, auditable pipeline from raw CSV data to "
        "production-ready model predictions. Every model is trained on a validated partition, "
        "evaluated on an untouched holdout, versioned on disk, and subject to human approval "
        "before it affects real decisions. The goal is to remove guesswork from credit "
        "underwriting and demand planning while keeping a human in the loop."
    )

    # -- Pipeline ---------------------------------------------------------------
    st.markdown("### The decision pipeline")
    st.markdown(
        "Each workflow follows the same five-stage pipeline. Every stage produces "
        "artifacts that are inspectable and reversible."
    )

    st.markdown("""
    | Stage | What happens | Where to find it |
    |-------|-------------|------------------|
    | **1. Upload data** | CSV records are parsed, profiled for quality (rows, missing cells, duplicates), and previewed. | Credit risk or Demand page |
    | **2. Map fields** | Column headers are matched to required fields via auto-suggestion. An exact-match / alias / invalid-family report flags problems before training. | Credit risk or Demand page |
    | **3. Validate** | The mapped dataset is checked for structural completeness and minimum row thresholds. Blocking errors prevent downstream steps. | Credit risk or Demand page |
    | **4. Train** | A model is trained on the labeled partition and evaluated on an untouched chronological holdout. Metrics (ROC-AUC, F1, MAE, R2, etc.) and a confusion breakdown are returned. | Training page |
    | **5. Deploy** | The trained model version is saved to the company workspace. The active version is the one used for live predictions. One-click rollback is available. | History page |
    """)

    st.markdown(
        "After deployment, the Credit risk and Demand pages run the **active model** "
        "against new uploads without retraining. Recommendations are generated by the "
        "governance engine, which applies your company rules on top of the raw prediction."
    )

    # -- Credit risk ------------------------------------------------------------
    st.markdown("### Credit risk workflow")
    st.markdown(
        "Upload labeled historical credit records. The system trains a classifier that "
        "outputs a risk score (0-1) and a tier (LOW / MEDIUM / HIGH) per customer. "
        "Explainability indicators highlight the features driving each score. "
        "The recommendation engine suggests actions (e.g. request additional documents, "
        "approve with conditions) filtered through your company's mandatory rules and "
        "forbidden-action keywords."
    )

    # -- Demand workflow --------------------------------------------------------
    st.markdown("### Demand workflow")
    st.markdown(
        "Upload historical sales or consumption data. The system trains a regressor that "
        "forecasts unit demand per period and flags anomalies and stockout risks. "
        "Evaluation metrics (MAE, RMSE, WAPE, R2) quantify forecast accuracy. "
        "The recommendation engine surfaces supply-chain actions such as pre-order "
        "triggers or safety-stock adjustments."
    )

    # -- Training ---------------------------------------------------------------
    st.markdown("### Training and model selection")
    st.markdown(
        "The Training page supports single-model, train-all, and grid-search modes. "
        "In train-all mode every available algorithm (XGBoost, LightGBM, Random Forest, "
        "Boosted Trees, etc.) is trained and the best composite score wins. "
        "Optional threshold optimization sweeps decision boundaries on the holdout to "
        "maximize F1 and PR-AUC. A controlled augmentation experiment can be run to "
        "measure whether synthetic minority-class examples improve recall without "
        "degrading precision."
    )

    # -- Governance -------------------------------------------------------------
    st.markdown("### Governance and versioning")
    st.markdown(
        "Each saved model version records its metrics, hyperparameters, data summary, "
        "and experiment type. The History page lists all versions and allows one-click "
        "activation or rollback. The Policies page lets administrators define mandatory "
        "recommendation rules, forbidden action keywords, and whether human approval is "
        "required before any recommendation is finalized."
    )

    # -- Quick reference --------------------------------------------------------
    st.markdown("### Quick reference")

    st.markdown("""
    1. **Configure workspace** -- Set company name, currency, and approval requirements on the Policies page.
    2. **Upload training data** -- Provide labeled historical records on the Training page.
    3. **Map and validate fields** -- Confirm the auto-suggested column mapping; resolve any invalid-family errors.
    4. **Train a model** -- Choose single-model, train-all, or grid-search. Review holdout metrics before saving.
    5. **Activate the model** -- Use the History page to set the newly trained version as the active model.
    6. **Run predictions** -- Upload new records on Credit risk or Demand. The active model scores them without retraining.
    7. **Review recommendations** -- The governance engine applies company rules. Human approval can be enforced.
    8. **Roll back if needed** -- History keeps every version. Reactivate a prior model at any time.
    """)

    st.markdown("---")
    st.markdown(
        "<small>Built for organizations that need auditable, versioned ML decisions "
        "with human oversight at every consequential step.</small>",
        unsafe_allow_html=True,
    )
